BookShop/ViewModels/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using BookShop.Models;

namespace BookShop.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Category> Categories { get; set; }
        public IEnumerable<Book> Books { get; set; }
        public IEnumerable<Book> Bestsellers { get; set; }



    }
}

BookShop/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookShop.DAL;

namespace BookShop.Controllers
{
    public class BookController : Controller
    {
        private BookShopContext db = new BookShopContext();
        // GET: Books
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List(string name, string searchQuery = null)
        {
            var category = db.Categories.Include("Books").Where(k => k.Name.ToUpper() == name.ToUpper()).Single();

            //var books = category.Books.ToList();

            var books = category.Books.Where(x => (searchQuery == null ||
                                                   x.Title.ToLower().Contains(searchQuery.ToLower()) ||
                                                   x.Writer.ToLower().Contains(searchQuery.ToLower())) &&
                                                  !x.Hidden);

            if (Request.IsAjaxRequest())
            {
                return PartialView("_BooksList", books);
            }

            return View(books);
        }

        public ActionResult Details(int id)
        {
            var book = db.Books.Find(id);
            return View(book);
        }

        [ChildActionOnly]
        [OutputCache(Duration = 86400)]
        public ActionResult CategoriesMenu()
        {
            
            var categories = db.Categories.ToList();
            return PartialView("_CategoriesMenu", categories);
        }

        public ActionResult BooksTips(string term)
        {
            var books = db.Books.Where(x => !x.Hidden && x.Title.ToLower().Contains(term.ToLower()))
                .Take(5).Select(x => new { label = x.Title });

            return Json(books, JsonRequestBehavior.AllowGet);
        }

    }
}

BookShop/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.EnterpriseServices;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookShop.DAL;
using BookShop.Infrastructure;
using BookShop.Models;
using BookShop.ViewModels;

namespace BookShop.Controllers
{
    public class HomeController : Controller
    {
        private BookShopContext db = new BookShopContext();

        public ActionResult Index()
        {
            ICacheProvider cache = new DefaultCacheProvider();

            //category
            List<Category> categories;

            if (cache.IsSet(Const.CategoryCacheKey))
            {
                categories = cache.Get(Const.CategoryCacheKey) as List<Category>;
            }
            else
            {
                categories = db.Categories.ToList();
                cache.Set(Const.CategoryCacheKey, categories, 60);
            }

            //new
            List<Book> newBooks;

            if (cache.IsSet(Const.NewCacheKey))
            {
                newBooks = cache.Get(Const.NewCacheKey) as List<Book>;
            }
            else
            {
                newBooks = db.Books.Where(x => !x.Hidden).OrderByDescending(x => x.AddDate).Take(3).ToList();
                cache.Set(Const.NewCacheKey, newBooks, 60);
            }

            //bestsellers
            List<Book> bestsellerBooks;

            if (cache.IsSet(Const.BestsellerCacheKey))
            {
                bestsellerBooks = cache.Get(Const.BestsellerCacheKey) as List<Book>;
            }
            else
            {
                bestsellerBooks = db.Books.Where(x => !x.Hidden && x.Bestseller).OrderBy(x => Guid.NewGuid()).Take(3).ToList();
                cache.Set(Const.BestsellerCacheKey, bestsellerBooks, 60);
            }
            

            var vm = new HomeViewModel()
            {
                Categories = categories,
                Books = newBooks,
                Bestsellers = bestsellerBooks
            };
            return View(vm);
        }

        public ActionResult StaticPages(string name)
        {
            return View(name);

        }
      
    }
}

BookShop/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>O nas</h2>
<br/>
<div>
    Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.
    Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.
    Fusce non varius purus aenean nec magna felis fusce vestibulum velit mollis odio sollicitudin lacinia aliquam posuere, sapien elementum lobortis tincidunt, turpis dui ornare nisl, sollicitudin interdum turpis nunc eget.
    Sem nulla eu ultricies orci praesent id augue nec lorem pretium congue sit amet ac nunc fusce iaculis lorem eu diam hendrerit at mattis purus dignissim vivamus mauris tellus, fringilla.
    Vel dapibus a, blandit quis erat vivamus elementum aliquam luctus etiam fringilla pretium sem vitae sodales mauris id nulla est praesent laoreet, metus vel auctor aliquam, eros purus vulputate leo.
    Eget consequat neque quam id tellus duis ultricies tempor tortor, vitae dignissim ligula mattis nec in hac habitasse platea dictumst ut arcu enim, dictum quis ultrices id, sagittis eget nulla.
    Sed nunc mi, congue ut ultricies ac, varius a eros donec porttitor, libero fermentum fringilla laoreet, eros arcu sodales ante, ut dictum risus lectus vel quam integer ultricies, nunc eget.
    Elementum euismod, orci enim vestibulum orci, nec suscipit urna odio et tellus suspendisse suscipit orci sit amet sem venenatis nec lobortis sem suscipit nullam nec imperdiet velit mauris eu nisi.
    A felis imperdiet porta at ac nulla vivamus faucibus felis nec dolor pretium eget pellentesque dolor suscipit maecenas vitae enim arcu, at tincidunt nunc pellentesque eleifend vulputate lacus, vel semper.
    Sem ornare sit amet proin sem sapien, auctor vel faucibus id, aliquet vitae ipsum etiam auctor ultricies ante, at dapibus urna viverra sed nullam mi arcu, tempor vitae interdum a.
    Sodales non urna vestibulum dignissim auctor mauris, ac elementum purus fermentum vitae duis placerat laoreet risus, sit amet eleifend tellus lobortis non vivamus iaculis dapibus leo a ornare cras vel.
    Sem at felis convallis mollis posuere ultrices dolor sed tellus arcu, accumsan a consectetur sit amet, volutpat eget lorem phasellus quis ipsum orci integer sodales tincidunt nibh a elementum ut.
    Ac libero nec orci euismod euismod nec at nulla duis malesuada faucibus porta aliquam nec consequat eros sed porttitor placerat dolor, accumsan imperdiet neque ornare in aenean non elit non.
    Leo porta mattis mauris non dolor nunc, id congue odio donec tellus nisl, semper id consectetur vitae, dapibus dictum nisl morbi sed augue purus sed dictum diam convallis tortor interdum.
    Volutpat phasellus dapibus arcu sit amet neque vulputate sed elementum orci fringilla in hac habitasse platea dictumst maecenas ut dui diam curabitur adipiscing vestibulum libero, nec varius dui pulvinar eget.
    Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; aliquam dui neque, varius eu laoreet vel.
</div>

BookShop/Views/Home/Community.cshtml
@{
    ViewBag.Title = "Comunity";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Społeczność</h2>
<br/>
<div>
    Varius nisl ac ipsum gravida vel pretium tellus tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu.
    Lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel placerat suscipit, orci nisl iaculis eros.
    A tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu.
    Ac ante fusce non varius purus aenean nec magna felis fusce vestibulum velit mollis odio sollicitudin lacinia aliquam posuere, sapien elementum lobortis.
    Tincidunt, turpis dui ornare nisl, sollicitudin interdum turpis nunc eget sem nulla eu ultricies orci praesent id augue nec lorem pretium congue.
    Sit amet ac nunc fusce iaculis lorem eu diam hendrerit at mattis purus dignissim vivamus mauris tellus, fringilla vel dapibus a, blandit.
    Quis erat vivamus elementum aliquam luctus etiam fringilla pretium sem vitae sodales mauris id nulla est praesent laoreet, metus vel auctor aliquam.
    Eros purus vulputate leo, eget consequat neque quam id tellus duis ultricies tempor tortor, vitae dignissim ligula mattis nec in hac habitasse.
    Platea dictumst ut arcu enim, dictum quis ultrices id, sagittis eget nulla sed nunc mi, congue ut ultricies ac, varius a eros.
    Donec porttitor, libero fermentum fringilla laoreet, eros arcu sodales ante, ut dictum risus lectus vel quam integer ultricies, nunc eget elementum euismod.
    Orci enim vestibulum orci, nec suscipit urna odio et tellus suspendisse suscipit orci sit amet sem venenatis nec lobortis sem suscipit nullam.
    Nec imperdiet velit mauris eu nisi a felis imperdiet porta at ac nulla vivamus faucibus felis nec dolor pretium eget pellentesque dolor.
    Suscipit maecenas vitae enim arcu, at tincidunt nunc pellentesque eleifend vulputate lacus, vel semper sem ornare sit amet proin sem sapien, auctor.
    Vel faucibus id, aliquet vitae ipsum etiam auctor ultricies ante, at dapibus urna viverra sed nullam mi arcu, tempor vitae interdum a.
    Sodales non urna vestibulum dignissim auctor mauris, ac elementum purus fermentum vitae duis placerat laoreet risus, sit amet eleifend tellus lobortis non.
    Vivamus iaculis dapibus leo a ornare cras vel sem at felis convallis mollis posuere ultrices dolor sed tellus arcu, accumsan a consectetur.
    Sit amet, volutpat eget lorem phasellus quis ipsum orci integer sodales tincidunt nibh a elementum ut ac libero nec orci euismod euismod.
    Nec at nulla duis malesuada faucibus porta aliquam nec consequat eros sed porttitor placerat dolor, accumsan imperdiet neque ornare in aenean non.
    Elit non leo porta mattis mauris non dolor nunc, id congue odio donec tellus nisl, semper id consectetur vitae, dapibus dictum nisl.
    Morbi sed augue purus sed dictum diam convallis tortor interdum volutpat phasellus dapibus arcu sit amet neque vulputate sed elementum orci fringilla.
    In hac habitasse platea dictumst maecenas ut dui diam curabitur adipiscing vestibulum libero, nec varius dui pulvinar eget vestibulum ante ipsum primis.
    In faucibus orci luctus et ultrices posuere cubilia curae; aliquam dui neque, varius eu laoreet vel.
</div>

BookShop/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Kontakt</h2>
<br/>
<div>
    Fusce vel sapien elit in malesuada semper mi.
    Id sollicitudin urna fermentum ut fusce varius nisl.
    Ac ipsum gravida vel pretium tellus tincidunt integer.
    Eu augue augue nunc elit dolor, luctus placerat.
    Scelerisque euismod, iaculis eu lacus nunc mi elit.
    Vehicula ut laoreet ac, aliquam sit amet justo.
    Nunc tempor, metus vel placerat suscipit, orci nisl.
    Iaculis eros, a tincidunt nisi odio eget lorem.
</div>

BookShop/Views/Home/Help.cshtml
@{
    ViewBag.Title = "Help";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Pomoc</h2>
<br/>
<div>
    Sapien elit in malesuada semper mi, id sollicitudin urna fermentum.
    Ut fusce varius nisl ac ipsum gravida vel pretium tellus.
    Tincidunt integer eu augue augue nunc elit dolor, luctus placerat.
    Scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut.
    Laoreet ac, aliquam sit amet justo nunc tempor, metus vel.
    Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio.
    Eget lorem nulla condimentum tempor mattis ut vitae feugiat augue.
    Cras ut metus a risus iaculis scelerisque eu ac ante.
    Fusce non varius purus aenean nec magna felis fusce vestibulum.
    Velit mollis odio sollicitudin lacinia aliquam posuere, sapien elementum lobortis.
</div>

BookShop/Views/Home/Index.cshtml
@model BookShop.ViewModels.HomeViewModel
@using BookShop.Infrastructure
@{
    ViewBag.Title = "Sklep z książkami";
}
<section>
    <nav class="category">
        <ul>
            @foreach (var category in Model.Categories)
            {
                <li>
                    <a href="@Url.Action("List", "Book", new { name = category.Name.ToLower() })"
                       style="background-image: url(@Url.IconsCategoriesPatch(category.NamePic));">
                        @category.Name
                    </a>
                </li>
            }


        </ul>

        @*<a href="@Url.Action("Index", "Home")">
                <img src="~/img/Other/books.jpg"  id="baner"/>
            </a>*@
    </nav>
</section>
<br/>
<br/>
<br/>
<br/>
<br/>

<section>
    <ul class="ThreeCollumnsBooks BookList">
        @foreach (var booknew in Model.Books)
        {
            <li>
                <article>
                    <a class="addToBasket" href="@Url.Action("AddToBasket", "Basket", new {id = booknew.BookId})">
                        <img src="../img/Other/basket.png" />
                        @*<i class="fa fa-shopping-cart fa-3x"></i>*@
                    </a>
                    <a class="bookDetails" href="@Url.Action("Details", "Book", new {id = booknew.BookId})">
                        <div class="newFlag"></div>
                        <img class="book" src="@Url.IconsBooksPatch(booknew.NamePic)" />
                        <h1>
                            @booknew.Title - @booknew.Writer
                        </h1>
                    </a>
                </article>
            </li>
        }
    </ul>
</section>

<section>
    <ul class="ThreeCollumnsBooks BookList">
        @foreach (var bestseller in Model.Bestsellers)
            {
            <li>
                <article>
                    <a class="addToBasket" href="@Url.Action("AddToBasket", "Basket", new {id = bestseller.BookId})">
                        <img src="../img/Other/basket.png" />
                    </a>
                    <a class="bookDetails" href="@Url.Action("Details", "Book", new {id = bestseller.BookId})">
                        <div class="bestsellerFlag"></div>
                        <img class="book" src="@Url.IconsBooksPatch(bestseller.NamePic)" />
                        <h1>
                            @bestseller.Title - @bestseller.Writer
                        </h1>
                    </a>
                </article>
            </li>
        }


    </ul>
</section>

BookShop/Views/Home/Opinions.cshtml
@{
    ViewBag.Title = "Opinions";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Opinie</h2>
<br/>
<div>
    Varius nisl ac ipsum gravida vel pretium tellus tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu.
    Lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel placerat suscipit, orci nisl iaculis eros.
    A tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu.
    Ac ante fusce non varius purus aenean nec magna felis fusce vestibulum velit mollis odio sollicitudin lacinia aliquam posuere, sapien elementum lobortis.
    Tincidunt, turpis dui ornare nisl, sollicitudin interdum turpis nunc eget sem nulla eu ultricies orci praesent id augue nec lorem pretium congue.
    Sit amet ac nunc fusce iaculis lorem eu diam hendrerit at mattis purus dignissim vivamus mauris tellus, fringilla vel dapibus a, blandit.
    Quis erat vivamus elementum aliquam luctus etiam fringilla pretium sem vitae sodales mauris id nulla est praesent laoreet, metus vel auctor aliquam.
    Eros purus vulputate leo, eget consequat neque quam id tellus duis ultricies tempor tortor, vitae dignissim ligula mattis nec in hac habitasse.
    Platea dictumst ut arcu enim, dictum quis ultrices id, sagittis eget nulla sed nunc mi, congue ut ultricies ac, varius a eros.
    Donec porttitor, libero fermentum fringilla laoreet, eros arcu sodales ante, ut dictum risus lectus vel quam integer ultricies, nunc eget elementum euismod.
    Orci enim vestibulum orci, nec suscipit urna odio et tellus suspendisse suscipit orci sit amet sem venenatis nec lobortis sem suscipit nullam.
    Augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel placerat suscipit, orci nisl iaculis eros.
    A tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante fusce non varius purus aenean nec magna felis fusce.
    Vestibulum velit mollis odio sollicitudin lacinia aliquam posuere, sapien elementum lobortis tincidunt, turpis dui ornare nisl, sollicitudin interdum turpis nunc eget sem nulla eu ultricies orci praesent id augue nec lorem pretium congue.
    Sit amet ac nunc fusce iaculis lorem eu diam hendrerit at mattis purus dignissim vivamus mauris tellus, fringilla vel dapibus a, blandit quis erat vivamus elementum aliquam luctus etiam fringilla pretium sem vitae.
    Sodales mauris id nulla est praesent laoreet, metus vel auctor aliquam, eros purus vulputate leo, eget consequat neque quam id tellus duis ultricies tempor tortor, vitae dignissim ligula mattis nec in hac habitasse.
    Platea dictumst ut arcu enim, dictum quis ultrices id, sagittis eget nulla sed nunc mi, congue ut ultricies ac, varius a eros donec porttitor, libero fermentum fringilla laoreet, eros arcu sodales ante, ut.
    Dictum risus lectus vel quam integer ultricies, nunc eget elementum euismod, orci enim vestibulum orci, nec suscipit urna odio et tellus suspendisse suscipit orci sit amet sem venenatis nec lobortis sem suscipit nullam.
    Nec imperdiet velit mauris eu nisi a felis imperdiet porta at ac nulla vivamus faucibus felis nec dolor pretium eget pellentesque dolor suscipit maecenas vitae enim arcu, at tincidunt nunc pellentesque eleifend vulputate.
    Lacus, vel semper sem ornare sit amet proin sem sapien, auctor vel faucibus id, aliquet vitae ipsum etiam auctor ultricies ante, at dapibus urna viverra sed nullam mi arcu, tempor vitae interdum a.
    Sodales non urna vestibulum dignissim auctor mauris, ac elementum purus fermentum vitae duis placerat laoreet risus, sit amet eleifend tellus lobortis non vivamus iaculis dapibus leo a ornare cras vel sem at felis.
    Convallis mollis posuere ultrices dolor sed tellus arcu, accumsan a consectetur sit amet, volutpat eget lorem phasellus quis ipsum orci integer sodales tincidunt nibh a elementum ut ac libero nec orci euismod euismod.
    Nec at nulla duis malesuada faucibus porta aliquam nec consequat eros sed porttitor placerat dolor, accumsan imperdiet neque ornare in aenean non elit non leo porta mattis mauris non dolor nunc, id congue.
    Odio donec tellus nisl, semper id consectetur vitae, dapibus dictum nisl morbi sed augue purus sed dictum diam convallis tortor interdum volutpat phasellus dapibus arcu sit amet neque vulputate sed elementum orci fringilla.
    In hac habitasse platea dictumst maecenas ut dui diam curabitur adipiscing vestibulum libero, nec varius dui pulvinar eget vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; aliquam dui.
    Neque, varius eu laoreet vel.
</div>

BookShop/Views/Home/Rules.cshtml
@{
    ViewBag.Title = "Regulations";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Regulamin</h2>
<br/>
<div>
    Fusce vel sapien elit in malesuada semper mi.
    Id sollicitudin urna fermentum ut fusce varius nisl.
    Ac ipsum gravida vel pretium tellus tincidunt integer.
    Eu augue augue nunc elit dolor, luctus placerat.
    Scelerisque euismod, iaculis eu lacus nunc mi elit.
    Vehicula ut laoreet ac, aliquam sit amet justo.
    Nunc tempor, metus vel placerat suscipit, orci nisl.
    Iaculis eros, a tincidunt nisi odio eget lorem.
    Nulla condimentum tempor mattis ut vitae feugiat augue.
    Cras ut metus a risus iaculis scelerisque eu.
    Ac ante fusce non varius purus aenean nec.
    Magna felis fusce vestibulum velit mollis odio sollicitudin.
    Lacinia aliquam posuere, sapien elementum lobortis tincidunt, turpis.
    Dui ornare nisl, sollicitudin interdum turpis nunc eget.
    Sem nulla eu ultricies orci praesent id augue.
    Nec lorem pretium congue sit amet ac nunc.
    Fusce iaculis lorem eu diam hendrerit at mattis.
    Purus dignissim vivamus mauris tellus, fringilla vel dapibus.
    A, blandit quis erat vivamus elementum aliquam luctus.
    Etiam fringilla pretium sem vitae sodales mauris id.
    Nulla est praesent laoreet, metus vel auctor aliquam.
    Eros purus vulputate leo, eget consequat neque quam.
    Id tellus duis ultricies tempor tortor, vitae dignissim.
    Ligula mattis nec in hac habitasse platea dictumst.
    Ut arcu enim, dictum quis ultrices id, sagittis.
    Eget nulla sed nunc mi, congue ut ultricies.
    Ac, varius a eros donec porttitor, libero fermentum.
    Fringilla laoreet, eros arcu sodales ante, ut dictum.
    Risus lectus vel quam integer ultricies, nunc eget.
    Elementum euismod, orci enim vestibulum orci, nec suscipit.
    Urna odio et tellus suspendisse suscipit orci sit.
    Amet sem venenatis nec lobortis sem suscipit nullam.
    Nec imperdiet velit mauris eu nisi a felis.
    Imperdiet porta at ac nulla vivamus faucibus felis.
    Nec dolor pretium eget pellentesque dolor suscipit maecenas.
    Vitae enim arcu, at tincidunt nunc pellentesque eleifend.
    Vulputate lacus, vel semper sem ornare sit amet.
    Proin sem sapien, auctor vel faucibus id, aliquet.
    Vitae ipsum etiam auctor ultricies ante, at dapibus.
    Urna viverra sed nullam mi arcu, tempor vitae.
    Interdum a, sodales non urna vestibulum dignissim auctor.
    Mauris, ac elementum purus fermentum vitae duis placerat.
    Laoreet risus, sit amet eleifend tellus lobortis non.
    Vivamus iaculis dapibus leo a ornare cras vel.
    Sem at felis convallis mollis posuere ultrices dolor.
    Sed tellus arcu, accumsan a consectetur sit amet.
    Volutpat eget lorem phasellus quis ipsum orci integer.
    Sodales tincidunt nibh a elementum ut ac libero.
    Nec orci euismod euismod nec at nulla duis.
    Malesuada faucibus porta aliquam nec consequat eros sed.
    Porttitor placerat dolor, accumsan imperdiet neque ornare in.
    Aenean non elit non leo porta mattis mauris.
    Non dolor nunc, id congue odio donec tellus.
    Nisl, semper id consectetur vitae, dapibus dictum nisl.
    Morbi sed augue purus sed dictum diam convallis.
    Tortor interdum volutpat phasellus dapibus arcu sit amet.
    Neque vulputate sed elementum orci fringilla in hac.
    Habitasse platea dictumst maecenas ut dui diam curabitur.
    Adipiscing vestibulum libero, nec varius dui pulvinar eget.
    Vestibulum ante ipsum primis in faucibus orci luctus.
    Et ultrices posuere cubilia curae; aliquam dui neque.
    Varius eu laoreet vel.
</div>